server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

jwt:
  secret: <jwt_secret>
